config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  resources :users
  resources :locations
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    if user.present?
      # if user.admin?
        can :manage, :all
        cannot :delete, User, is_admin: true
      # else
        # can :edit, User, :id => user.id
        # can :read, User, :id => user.id
      # end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  acts_as_nested_set
  self.inheritance_column = nil
  belongs_to :created_by, class_name: User.to_s
  belongs_to :parent, class_name: Location.to_s

  LOCATION_TYPES = {
    division: 'Division',
    district: 'District',
    tehsil: 'Tehsil',
    union_council: 'Union Council'
  }.freeze

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar
  has_many :locations, foreign_key: :created_by_id, dependent: :nullify
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception, prepend: true
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  rescue_from ActiveRecord::RecordNotFound do |exception|
    respond_to do |format|
      format.html { redirect_to root_url, alert: 'Resource doesn\'t exist' }
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :avatar])
    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:email)
    end
  end 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    respond_to do |format|
      format.html
    end
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  load_and_authorize_resource

  # GET /locations
  def index
    @locations = @locations.paginate(page: params[:page], per_page: 10)
    respond_to do |format|
      format.html
    end
  end
  
  # GET /locations/:id
  def show
    respond_to do |format|
      format.html
    end
  end

  # GET /locations/new
  def new
    @locations = Location.all
    respond_to do |format|
      format.html
    end
  end

  # POST /locations
  def create
    @location.save
    respond_to do |format|
      format.html { redirect_to action: :index }
    end
  end

  # GET /locations/:id
  def edit
    respond_to do |format|
      format.html
    end
  end

  # PUT/PATCH /locations/:id
  def update
    respond_to do |format|
      format.html
    end
  end

  # DELETE /locations/:id
  def destroy
    respond_to do |format|
      format.html
    end
  end

  private

  def location_params
    params.require(:location).permit(:name, :description, :type, :parent_id, :created_by_id)
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  layout 'public_application'

  # GET /resource/sign_in
  # def new
  #   super
  #   respond_to do |format|
  #     format.html render
  #   end
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :side_bar_menu
  load_and_authorize_resource

  # GET /users
  def index
    @sub_tree_menu = 'index'
    @users = @users.paginate(page: params[:page], per_page: 10)
    respond_to do |format|
      format.html
    end
  end

  # GET /users/:id
  def show
    respond_to do |format|
      format.html
    end
  end

  # GET /users/new
  def new
    @sub_tree_menu = 'index'
    respond_to do |format|
      format.html
    end
  end

  # POST /users
  def create
    respond_to do |format|
      format.html { redirect_to :index }
    end
  end

  # PUT/PATCH /users/:id
  def edit
  end

  # DELETE /users/:id
  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :mobile, :address, :avatar)
  end

  def side_bar_menu
    @tree_menu = 'users'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<!-- Default box -->
<div class="card">
  <div class="card-header">
    <h3 class="card-title">Title</h3>

    <div class="card-tools">
      <button type="button" class="btn btn-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
        <i class="fas fa-minus"></i></button>
      <button type="button" class="btn btn-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
        <i class="fas fa-times"></i></button>
    </div>
  </div>
  <div class="card-body">
    Start creating your amazing application!
  </div>
  <!-- /.card-body -->
  <div class="card-footer">
    Footer
  </div>
  <!-- /.card-footer-->
</div>
<!-- /.card -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Feedback Portal | Login</title>
    
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

      <!-- Font Awesome -->
    <link rel="stylesheet" href="/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

    <%= yield :stylesheets %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="hold-transition sidebar-mini">
    <div class="wrapper">

      <%= render 'shared/top_navigation_bar' %>
      <%= render 'shared/sidebar' %>

      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <div class="container-fluid">
            <div class="row mb-2">
              <div class="col-sm-6">
                <h1><%= yield :page_header %><h2>
              </div>
            </div>
          </div><!-- /.container-fluid -->
        </section>

        <% if notice.present? %>
          <p class="notice"><%= notice %></p>
        <% end %>

        <% if alert.present? %>
          <p class="alert"><%= alert %></p>
        <% end %>

        <!-- Main content -->
        <section class="content">
          <%= yield %>
        </section>
      </div><!-- /.content-wrapper -->
      <footer class="main-footer">
        <div class="float-right d-none d-sm-block">
          <b>Version</b> 3.0.0-beta.2
        </div>
        <strong>Copyright &copy; 2014-2019 <a href="#_">KPK Government</a>.</strong> All rights
        reserved.
      </footer>
    </div><!-- /.wrapper -->

    <!-- jQuery -->
    <script src="/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- FastClick -->
    <script src="/plugins/fastclick/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="/dist/js/adminlte.min.js"></script>
    <%= yield :javascripts %>
  </body>
</html>

app/views/layouts/public_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Feedback Portal | Login</title>
    
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

      <!-- Font Awesome -->
    <link rel="stylesheet" href="/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="hold-transition login-page">
    <div class="login-box">
      <div class="login-logo">
        <a href="_#"><b>Complaint Management</b> Portal</a>
      </div>
      
      <% if notice.present? %>
        <p class="notice"><%= notice %></p>
      <% end %>

      <% if alert.present? %>
        <p class="alert"><%= alert %></p>
      <% end %>

      <%= yield %>
    </div>
    <!-- jQuery -->
    <script src="/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <%= hidden_field 'location', :created_by_id, value: @current_user.id %>
  <div class="card-body">
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control col-6', placeholder: 'Name', required: true %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control col-6', placeholder: 'Description' %>
    </div>
    <div class="form-group">
      <%= f.label :type %>
      <%= f.select :type, options_for_select(Location::LOCATION_TYPES.invert), { include_blank: false }, class: 'form-control col-6' %>
    </div>
    <div class="form-group">
      <%= f.label :parent_location %>
      <%= f.select :parent_id, options_from_collection_for_select(@locations, :id, :name), { include_blank: '--' }, class: 'form-control col-6' %>
    </div>
  </div>
  <div class="card-footer">
    <%= f.submit('Submit', class: 'btn btn-primary') %>
  </div>
<% end %>

app/views/locations/_location.html.erb
<tr>
  <td><%= location.id %></td>
  <td><%= location.name %></td>
  <td><%= location.type.humanize %></td>
  <td><%= location.parent.try(:name) || '--' %>
  <td><%= location.created_at.to_s(:long) %></td>
  <td><%= location.created_by.try(:name) || '--' %>
</tr>

app/views/locations/index.html.erb
<% content_for :page_header do %>
  Locations
<% end %>
<!-- Default box -->
<div class="card">
  <div class="card-header">
    <h3 class="card-title">Current Locations</h3>
    <div class="card-tools">
      <a type="button" href="<%= new_location_path %>" class="btn btn-sm btn-primary pull-right"><i class="fa fa-plus"></i> Add Location</a>
    </div>
  </div>
  <div class="card-body table-responsive p-0">
    <table class="table table-hover table-bordered">
      <thead>
        <tr>
          <th>Id</th>
          <th>Name</th>
          <th>Type</th>
          <th>Parent Location</th>
          <th>Added On</th>
          <th>Created by</th>
        </tr>
      </thead>
      <tbody>
        <%= render @locations %>
      </tbody>
    </table>
  </div>
  <div class="card-footer">
    <%= will_paginate @locations %>
  </div> <!-- /.card-footer-->
</div><!-- /.card -->

app/views/locations/new.html.erb
<% content_for :page_header do %>
  Add New Location
<% end %>
<!-- Default box -->
<div class="card card-primary">
  <div class="card-header">
    <h3 class="card-title">Location Details</h3>
    <div class="card-tools">
    </div>
  </div>
  <%= render 'form' %>
</div>
<!-- /.card -->

app/views/shared/_sidebar.html.erb
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <a href="_#" class="brand-link">
    <img src="../../dist/img/AdminLTELogo.png"
          alt="AdminLTE Logo"
          class="brand-image img-circle elevation-3"
          style="opacity: .8">
    <span class="brand-text font-weight-light">AdminLTE 3</span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user -->
    <% if current_user.present? %>
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block"><%= current_user.email %></a>
        </div>
      </div>
    <% end %>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
            with font-awesome or any other icon font library -->
        <% if can? :manage, User %>
          <li class="nav-item has-treeview <%= @tree_menu == 'users' ? 'menu-open' : '' %>">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-users"></i>
              <p>
                User Management
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="<%= users_path %>" class="nav-link <%= @sub_tree_menu == 'index' ? 'active' : '' %>">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Users</p>
                </a>
              </li>
            </ul>
          </li>
        <% end %>

        <li class="nav-item has-treeview <%= @tree_menu == 'locations' ? 'menu-open' : '' %>">
          <a href="#" class="nav-link">
            <i class="nav-icon fas fa-globe-asia"></i>
            <p>
              Location Management
              <i class="fas fa-angle-left right"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="<%= locations_path %>" class="nav-link <%= @sub_tree_menu == 'index' ? 'active' : '' %>">
                <i class="far fa-circle nav-icon"></i>
                <p>Locations</p>
              </a>
            </li>
          </ul>
        </li>

      </ul> <!-- end of sidebar treeview -->
    </nav>
  </div>
</aside>

app/views/shared/_top_navigation_bar.html.erb
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="_#" class="nav-link">Home</a>
    </li>
  </ul>

  <!-- SEARCH FORM -->
  <form class="form-inline ml-3">
    <div class="input-group input-group-sm">
      <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
      <div class="input-group-append">
        <button class="btn btn-navbar" type="submit">
          <i class="fas fa-search"></i>
        </button>
      </div>
    </div>
  </form>

  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">
    <li class="nav-item">
      <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
    </li>
  </ul>
</nav>

app/views/users/_form.html.erb
<% content_for :page_header do %>
  Add New User
<% end %>
<%= form_for(@user) do |f| %>
  <div class="card-body">
    <div class="form-group">
      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: 'form-control col-6', placeholder: 'First Name' %>
    </div>
    <div class="form-group">
      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: 'form-control col-6', placeholder: 'Last Name' %>
    </div>
    <div class="form-group">
      <%= f.label :email_name %>
      <%= f.email_field :email, class: 'form-control col-6', placeholder: 'Email' %>
    </div>
    <div class="form-group">
      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control col-6', placeholder: 'Address' %>
    </div>
    <div class="form-group">
      <%= f.label :mobile %>
      <%= f.text_field :mobile, class: 'form-control col-6', placeholder: 'Mobile #' %>
    </div>
    <div class="form-group">
      <%= f.label :profile_picture %>
      <div class="input-group">
        <div class="custom-file col-6">
          <%= f.file_field :avatar, class: 'custom-file-input' %>
          <label class="custom-file-label">Choose Picture</label>
        </div>
      </div>
    </div>
  </div>
  <div class="card-footer">
    <%= f.submit('Submit', class: 'btn btn-primary') %>
  </div>
<% end %>

app/views/users/_user.html.erb
<tr>
  <td><%= user.id %></td>
  <td><%= user.email %></td>
  <td><%= user.first_name || '--' %></td>
  <td><%= user.last_name || '--' %></td>
  <td><%= user.address || '--' %></td>
  <td><%= user.mobile || '--' %></td>
</tr>

app/views/users/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>User#destroy</h1>
<p>Find me in app/views/user/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>User#edit</h1>
<p>Find me in app/views/user/edit.html.erb</p>

app/views/users/index.html.erb
<% content_for :page_header do %>
  Users
<% end %>
<!-- Default box -->
<div class="card">
  <div class="card-header">
    <h3 class="card-title">Current Users</h3>
    <div class="card-tools">
      <a type="button" href="<%= new_user_path %>" class="btn btn-sm btn-primary pull-right"><i class="fa fa-plus"></i> Add User</a>
    </div>
  </div>
  <div class="card-body table-responsive p-0">
    <table class="table table-hover table-bordered">
      <thead>
        <tr>
          <th>Id</th>
          <th>Email</th>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Address</th>
          <th>Mobile #</th>
        </tr>
      </thead>
      <tbody>
        <%= render @users %>
      </tbody>
    </table>
  </div>
  <div class="card-footer">
    <%= will_paginate @users %>
  </div> <!-- /.card-footer-->
</div><!-- /.card -->

app/views/users/new.html.erb
<!-- Default box -->
<div class="card card-primary">
  <div class="card-header">
    <h3 class="card-title">User Details</h3>
    <div class="card-tools">
    </div>
  </div>
  <%= render 'form' %>
</div><!-- /.card -->

app/views/users/show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>